import { Vazirmatn } from "next/font/google";
import { Providers } from '../providers';

import "@/app/globals.css";

const vazirmatn = Vazirmatn({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
  return (
    <html lang="en">
      <body className={vazirmatn.className}>
        <Providers>
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
