import { Inter } from "next/font/google";
import { Providers } from '../providers';

import "@/app/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <header>
            {/* Global Header */}
            <nav>
              <a href="#">dashboard</a>
            </nav>
          </header>
          <main>{children}</main>
          <footer>
            {/* Global Footer */}
          </footer>
        </Providers>
      </body>
    </html>
  );
}
